name: Trigger Netlify Build

on:
  push:
    branches:
      - main

jobs:
  trigger-netlify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build and Clear Cache
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"clear_cache": true}' \
          https://api.netlify.com/build_hooks/67451d8bf6d3ed79d739f4e9
